export default [
  {
    id: 0,
    imageSrc: '/images/teams/dr_toros_judit.jpg',
    name: 'dr. Törös Judit',
    title: 'alapító, irodavezető ügyvéd',
    description:
      'Az iroda ügyvezető partnere, aki a hosszútávú stratégiáért felel és szakmailag koordinálja a kulcsfontosságú tranzakciókat, megbízásokat',
    details: [
      'széleskörű peres képviselet választottbíróság és rendes bíróságok előtt',
      'kiemelt M&A tranzakciókban való részvétel, az ahhoz kapcsolódó teljes körű jogi átvilágítási eljárások koordinálása',
      'Bridge Budapest Vállalható Üzleti Kultúráért nagykövete',
      'magyar, angol, német',
    ],
  },

  {
    id: 1,
    imageSrc: '/images/teams/dr_fekete_zita.jpg',
    name: 'dr. Fekete Zita L.L.M.',
    title: 'ügyvéd, partner, közbeszerzési szakjogász',
    description: 'Az iroda banki ügyfeleit kiszolgáló munkacsoport vezetéséért, koordinációjáért felelős ügyvéd',
    details: [
      'széleskörű polgári peres tapasztalat',
      'követeléskezelés',
      'európai uniós támogatások jogi és közbeszerzési szempontú ellenőrzése, mind támogatói, mind felhasználói oldalról',
      'magyar, angol',
    ],
  },
  {
    id: 2,
    imageSrc: '/images/teams/tobias_rita.jpg',
    name: 'Tóbiás Rita',
    title: 'közgazdász, partner',
    description: 'Az iroda gazdasági-pénzügyi vezetője, aki a zavartalan jogi munka gazdasági hátterét biztosítja',
    details: [
      'közreműködés az iroda működéséhez és üzemeltetéséhez kapcsolódó szerződéskötések előkészítésében',
      'kapcsolattartás ügyfelekkel és az együttműködő partnerekkel',
      'megbízásokhoz kapcsolódó kimutatások, elemzések készítése',
      'az iroda gazdasági-pénzügyi működésének teljes körű támogatása',
      'magyar, angol',
    ],
  },
  {
    id: 3,
    imageSrc: '/images/teams/dr_kapetz_monika.jpg',
    name: 'dr. Kapetz Mónika L.L.M.',
    title: 'ügyvéd, ingatlanforgalmi-és versenyjogi szakjogász',
    description: '',
    details: [
      'részvétel M&A tranzakciókban, a tranzakciókhoz kapcsolódó jogi átvilágításban történő közreműködés',
      'ingatlanokkal kapcsolatos jogi feladatok teljes körű ellátása, okiratszerkesztés és véleményezés',
      'társasági jogi feladatok ellátása, cégbírósági eljárások lefolytatása',
      'magyar, angol',
    ],
  },
  {
    id: 4,
    imageSrc: '/images/teams/dr_sztvorecz_zsuzsa.jpg',
    name: 'dr. Sztvorecz Zsuzsa',
    title: 'ügyvéd, mediátor',
    description: '',
    details: [
      'peres eljárásokban teljes körű jogi képviselet ellátása',
      'pénzintézeti tevékenységgel kapcsolatos jogi feladatok ellátása, követeléskezelés ingatlanokkal kapcsolatos jogi feladatok teljes körű ellátása, okiratszerkesztés és véleményezés',
      'családjog',
      'mediátori tevékenység közvetítői eljárásokban',
      'magyar, angol',
    ],
  },
  {
    id: 5,
    imageSrc: '/images/teams/dr_cserep_edit.jpg',
    name: 'dr. Cserép Edit',
    title: 'ügyvéd',
    description: '',
    details: [
      'munkajoggal kapcsolatos feladatok teljes körű ellátása, peres képviselet, okiratszerkesztés',
      'szellemi tulajdon oltalmával kapcsolatos jogi tanácsadás, védjegy bejegyzési eljárásokban jogi képviselet ellátása, felhasználási szerződések szerkesztése, véleményezése',
      'adatvédelemmel kapcsolatos jogi tanácsadás, adatvédelmi szabályzatok, tájékoztatók elkészítése',
      'ngatlanokkal és gazdasági társaságokkal kapcsolatos jogi feladatok ellátása',
      'magyar, angol',
    ],
  },
  {
    id: 6,
    imageSrc: '/images/teams/dr_tengeri_anita.jpg',
    name: 'dr. Tengeri Anita',
    title: 'ügyvéd',
    description: '',
    details: [
      'ingatlanokkal kapcsolatos jogi feladatok teljes körű ellátása, okiratszerkesztés és véleményezés, részvétel új építésű ingatlan projektekben',
      'társasági jogi feladatok teljes körű ellátása',
      'szerződésből eredő, valamint szerződésen kívüli jogviták rendezése során teljes körű jogi képviselet ellátása',
      'magyar, angol',
    ],
  },
  {
    id: 7,
    imageSrc: '/images/teams/dr_kocsis_klaudia.jpg',
    name: 'dr. Kocsis Klaudia LL.M.',
    title: 'tőkepiaci és bank szakjogász',
    description: '',
    details: [
      'széleskörű peres képviselet',
      'társasági-és ingatlanjoggal kapcsolatos jogi feladatok teljes körű ellátása',
      'több éves jogtanácsosi tapasztalat multinacionális pénzügyi vállalkozásnál',
      'magyar, angol',
    ],
  },
  {
    id: 8,
    imageSrc: '/images/teams/dr_szentmihalyi_judit.jpg',
    name: 'dr. Szentmihályi Judit',
    title: 'ügyvéd',
    description: '',
    details: [
      'peres és peren kívüli jogi képviselet ellátása polgári, büntető, végrehajtási és szabadalmi ügyekben',
      'hitelintézetek, pénzügyi vállalkozások, biztosító társaságok jogi képviseletének ellátása választottbírósági, peres és Pénzügyi Békéltető Testület előtti eljárásokban, követeléskezelés',
      'befektetési alapok tevékenységéhez kapcsolódó jogvélemények készítése, közreműködés átvilágítási eljárásokban',
      'magyar, angol',
    ],
  },
  {
    id: 9,
    imageSrc: '/images/teams/dr_horvath_dorina.jpg',
    name: 'dr. Horváth Dorina',
    title: 'ügyvédjelölt',
    description: '',
    details: [
      'polgári peres eljárásokban, valamint Pénzügyi Békéltető Testület előtti pénzügyi fogyasztói jogvita rendezésére irányuló eljárásokban jogi képviselet ellátása',
      'ingatlan-és társasági joggal kapcsolatos okiratok szerkesztése, véleményezése, jogi állásfoglalások készítése, közreműködés M&A tranzakciókban és az ahhoz kapcsolódó átvilágítási eljárásokban',
      'kintlévőségkezelés',
      'magyar, német',
    ],
  },
  {
    id: 10,
    imageSrc: '/images/teams/dr_rajnoki_adrienn.jpg',
    name: 'dr. Rajnóki Adrienn',
    title: 'ügyvédjelölt',
    description: '',
    details: [
      'peres és Pénzügyi Békéltető Testület előtti eljárásokban jogi képviselet ellátása',
      'munka-és társasági joggal kapcsolatos okiratok szerkesztése, véleményezése, jogi képviselet ellátása cégeljárások során',
      'ingatlanokkal kapcsolatos jogi feladatok teljes körű ellátása, közreműködés átvilágítási eljárásokban',
      'EJEB előtti eljárásokban közreműködés',
      'magyar, angol',
    ],
  },
  {
    id: 11,
    imageSrc: '/images/teams/laszlo_vanda.jpg',
    name: 'László Vanda',
    title: 'irodavezető asszisztens',
    description: 'Az iroda lelke, aki a zavartalan jogi munka adminisztratív háttértámogatását biztosítja',
    details: [
      'kapcsolattartás ügyfelekkel',
      'ügyvédek és ügyvédjelöltek munkájának teljes körű támogatása',
      'peres eljárásokban kimutatások készítése',
      'magyar, angol',
    ],
  },
]
